# Generated by Django 3.1.2 on 2021-01-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210110_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-topic'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
    ]
