# Generated by Django 3.1.2 on 2021-01-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210110_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescope',
            options={'ordering': ['-main'], 'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематика статей'},
        ),
    ]
